//ACTION
export const GET_DANHSACHPHIM = 'GET_DANHSACHPHIM'

export const SET_DANH_SACH_PHIM_DANG_CHIEU = 'SET_DANH_SACH_PHIM_DANG_CHIEU'

export const SET_DANH_SACH_PHIM_SAP_CHIEU = 'SET_DANH_SACH_PHIM_SAP_CHIEU'

export const SET_THONG_TIN_PHIM = 'SET_THONG_TIN_PHIM'

//SAGA
export const GET_DANHSACHPHIM_SAGA = 'GET_DANHSACHPHIM_SAGA'


